# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mise/documents/github/repository/json_parser

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mise/documents/github/repository/json_parser

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mise/documents/github/repository/json_parser/CMakeFiles /Users/mise/documents/github/repository/json_parser/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mise/documents/github/repository/json_parser/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.o: Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.c.o

.PHONY : Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.o

# target to build an object file
Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.c.o
.PHONY : Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.c.o

Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.i: Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.c.i

.PHONY : Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.i

# target to preprocess a source file
Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.c.i
.PHONY : Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.c.i

Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.s: Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.c.s

.PHONY : Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.s

# target to generate assembly for a file
Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.c.s
.PHONY : Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.c.s

json_array.o: json_array.c.o

.PHONY : json_array.o

# target to build an object file
json_array.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_array.c.o
.PHONY : json_array.c.o

json_array.i: json_array.c.i

.PHONY : json_array.i

# target to preprocess a source file
json_array.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_array.c.i
.PHONY : json_array.c.i

json_array.s: json_array.c.s

.PHONY : json_array.s

# target to generate assembly for a file
json_array.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_array.c.s
.PHONY : json_array.c.s

json_common.o: json_common.c.o

.PHONY : json_common.o

# target to build an object file
json_common.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_common.c.o
.PHONY : json_common.c.o

json_common.i: json_common.c.i

.PHONY : json_common.i

# target to preprocess a source file
json_common.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_common.c.i
.PHONY : json_common.c.i

json_common.s: json_common.c.s

.PHONY : json_common.s

# target to generate assembly for a file
json_common.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_common.c.s
.PHONY : json_common.c.s

json_keyandvalue.o: json_keyandvalue.c.o

.PHONY : json_keyandvalue.o

# target to build an object file
json_keyandvalue.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_keyandvalue.c.o
.PHONY : json_keyandvalue.c.o

json_keyandvalue.i: json_keyandvalue.c.i

.PHONY : json_keyandvalue.i

# target to preprocess a source file
json_keyandvalue.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_keyandvalue.c.i
.PHONY : json_keyandvalue.c.i

json_keyandvalue.s: json_keyandvalue.c.s

.PHONY : json_keyandvalue.s

# target to generate assembly for a file
json_keyandvalue.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_keyandvalue.c.s
.PHONY : json_keyandvalue.c.s

json_number.o: json_number.c.o

.PHONY : json_number.o

# target to build an object file
json_number.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_number.c.o
.PHONY : json_number.c.o

json_number.i: json_number.c.i

.PHONY : json_number.i

# target to preprocess a source file
json_number.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_number.c.i
.PHONY : json_number.c.i

json_number.s: json_number.c.s

.PHONY : json_number.s

# target to generate assembly for a file
json_number.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_number.c.s
.PHONY : json_number.c.s

json_object.o: json_object.c.o

.PHONY : json_object.o

# target to build an object file
json_object.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_object.c.o
.PHONY : json_object.c.o

json_object.i: json_object.c.i

.PHONY : json_object.i

# target to preprocess a source file
json_object.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_object.c.i
.PHONY : json_object.c.i

json_object.s: json_object.c.s

.PHONY : json_object.s

# target to generate assembly for a file
json_object.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_object.c.s
.PHONY : json_object.c.s

json_string.o: json_string.c.o

.PHONY : json_string.o

# target to build an object file
json_string.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_string.c.o
.PHONY : json_string.c.o

json_string.i: json_string.c.i

.PHONY : json_string.i

# target to preprocess a source file
json_string.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_string.c.i
.PHONY : json_string.c.i

json_string.s: json_string.c.s

.PHONY : json_string.s

# target to generate assembly for a file
json_string.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_string.c.s
.PHONY : json_string.c.s

json_value.o: json_value.c.o

.PHONY : json_value.o

# target to build an object file
json_value.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_value.c.o
.PHONY : json_value.c.o

json_value.i: json_value.c.i

.PHONY : json_value.i

# target to preprocess a source file
json_value.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_value.c.i
.PHONY : json_value.c.i

json_value.s: json_value.c.s

.PHONY : json_value.s

# target to generate assembly for a file
json_value.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/json_value.c.s
.PHONY : json_value.c.s

test.o: test.c.o

.PHONY : test.o

# target to build an object file
test.c.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.c.o
.PHONY : test.c.o

test.i: test.c.i

.PHONY : test.i

# target to preprocess a source file
test.c.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.c.i
.PHONY : test.c.i

test.s: test.c.s

.PHONY : test.s

# target to generate assembly for a file
test.c.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.c.s
.PHONY : test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.o"
	@echo "... Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.i"
	@echo "... Users/mise/documents/github/repository/c_libraries/iobuffer/iobuffer.s"
	@echo "... json_array.o"
	@echo "... json_array.i"
	@echo "... json_array.s"
	@echo "... json_common.o"
	@echo "... json_common.i"
	@echo "... json_common.s"
	@echo "... json_keyandvalue.o"
	@echo "... json_keyandvalue.i"
	@echo "... json_keyandvalue.s"
	@echo "... json_number.o"
	@echo "... json_number.i"
	@echo "... json_number.s"
	@echo "... json_object.o"
	@echo "... json_object.i"
	@echo "... json_object.s"
	@echo "... json_string.o"
	@echo "... json_string.i"
	@echo "... json_string.s"
	@echo "... json_value.o"
	@echo "... json_value.i"
	@echo "... json_value.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

